"""Executable tests for the internal ProofOS PostgreSQL exemplar."""

from __future__ import annotations

import os
import shutil
import subprocess
import sys
import time
from pathlib import Path

import pytest
from pydantic import ValidationError

from mcp_audit.proofos_postgres import (
    LockMode,
    PhaseArtifact,
    PostgresBinaries,
    PostgresMigrationManifest,
    _bounded_process_output,
    _DisposablePostgres,
    digest_bytes,
    postgres_migration_json_schema,
    verify_postgres_migration,
)

_BASELINE = """
CREATE SCHEMA app;
CREATE TABLE app.accounts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email text NOT NULL
);
INSERT INTO app.accounts (email) VALUES ('ada@example.test'), ('grace@example.test');
"""

_EXPAND = """
ALTER TABLE app.accounts ADD COLUMN display_name text;
ALTER TABLE app.accounts
  ADD CONSTRAINT accounts_display_name_len
  CHECK (display_name IS NULL OR length(display_name) <= 100) NOT VALID;
"""

_EXPAND_ROLLBACK = """
ALTER TABLE app.accounts DROP CONSTRAINT accounts_display_name_len;
ALTER TABLE app.accounts DROP COLUMN display_name;
"""

_VALIDATE = """
ALTER TABLE app.accounts VALIDATE CONSTRAINT accounts_display_name_len;
"""

_VALIDATE_ROLLBACK = """
ALTER TABLE app.accounts DROP CONSTRAINT accounts_display_name_len;
ALTER TABLE app.accounts
  ADD CONSTRAINT accounts_display_name_len
  CHECK (display_name IS NULL OR length(display_name) <= 100) NOT VALID;
"""

_INDEX = """
CREATE INDEX CONCURRENTLY accounts_email_lower_idx ON app.accounts ((lower(email)));
"""

_INDEX_ROLLBACK = """
DROP INDEX CONCURRENTLY app.accounts_email_lower_idx;
"""


def _phase(
    phase_id: str,
    sql: str,
    rollback_sql: str,
    *,
    mode: str = "transactional",
    effect: str = "schema",
    lock: str = "AccessExclusiveLock",
    expected_object: str = "app.accounts",
    rollback_effect: str | None = None,
    rollback_lock: str | None = None,
    rollback_expected_object: str | None = None,
) -> dict[str, object]:
    return {
        "phase_id": phase_id,
        "mode": mode,
        "sql_digest": digest_bytes(sql.encode()),
        "rollback_type": "compensating_sql" if mode == "nontransactional" else "transaction",
        "rollback_digest": digest_bytes(rollback_sql.encode()),
        "declared_effects": [effect],
        "expected_objects": [expected_object],
        "max_lock_mode": lock,
        "rollback_effects": [rollback_effect or effect],
        "rollback_expected_objects": [rollback_expected_object or expected_object],
        "rollback_max_lock_mode": rollback_lock or lock,
    }


def _manifest(
    phases: list[dict[str, object]] | None = None,
) -> PostgresMigrationManifest:
    if phases is None:
        phases = [
            _phase("expand", _EXPAND, _EXPAND_ROLLBACK),
            _phase(
                "validate",
                _VALIDATE,
                _VALIDATE_ROLLBACK,
                lock="ShareUpdateExclusiveLock",
                rollback_lock="AccessExclusiveLock",
            ),
            _phase(
                "index",
                _INDEX,
                _INDEX_ROLLBACK,
                mode="nontransactional",
                effect="index",
                lock="ShareUpdateExclusiveLock",
                expected_object="app.accounts_email_lower_idx",
                rollback_expected_object="app.accounts_email_lower_idx",
            ),
        ]
    return PostgresMigrationManifest.model_validate(
        {
            "contract": {
                "contract_id": "proofos.postgres-migration",
                "contract_version": "0.1.0",
                "profile": "research-mvp",
            },
            "artifact_id": "accounts-expand-contract",
            "target_postgres_major": 16,
            "baseline_sql_digest": digest_bytes(_BASELINE.encode()),
            "migration_role": "proofos_migrator",
            "fixed_search_path": ["pg_catalog", "app"],
            "observed_tables": [{"schema_name": "app", "table_name": "accounts", "order_by": ["id"]}],
            "lock_timeout_ms": 2_000,
            "statement_timeout_ms": 20_000,
            "phases": phases,
        }
    )


def _manifest_for_baseline(
    baseline: str,
    phases: list[dict[str, object]],
    tables: list[dict[str, object]],
) -> PostgresMigrationManifest:
    payload = _manifest(phases).model_dump(mode="json")
    payload["baseline_sql_digest"] = digest_bytes(baseline.encode())
    payload["observed_tables"] = tables
    return PostgresMigrationManifest.model_validate(payload)


def _artifacts() -> dict[str, PhaseArtifact]:
    return {
        "expand": PhaseArtifact(sql=_EXPAND, rollback_sql=_EXPAND_ROLLBACK),
        "validate": PhaseArtifact(sql=_VALIDATE, rollback_sql=_VALIDATE_ROLLBACK),
        "index": PhaseArtifact(sql=_INDEX, rollback_sql=_INDEX_ROLLBACK),
    }


def _postgres_bindir() -> Path | None:
    configured = os.environ.get("PROOFOS_POSTGRES_BIN")
    candidates = [
        Path(configured) if configured else None,
        Path("/opt/homebrew/opt/postgresql@16/bin"),
        Path("/usr/local/opt/postgresql@16/bin"),
    ]
    pg_config = shutil.which("pg_config")
    if pg_config:
        result = subprocess.run(
            [pg_config, "--bindir"], check=False, capture_output=True, text=True, timeout=5
        )
        if result.returncode == 0:
            candidates.append(Path(result.stdout.strip()))
    for candidate in candidates:
        if candidate and (candidate / "postgres").is_file():
            return candidate
    return None


_BINDIR = _postgres_bindir()
requires_postgres = pytest.mark.skipif(_BINDIR is None, reason="PostgreSQL 16 binaries unavailable")


def _dummy_binaries() -> PostgresBinaries:
    root = Path("/nonexistent")
    return PostgresBinaries.model_construct(
        bindir=root,
        postgres=root / "postgres",
        initdb=root / "initdb",
        pg_ctl=root / "pg_ctl",
        psql=root / "psql",
        createdb=root / "createdb",
        dropdb=root / "dropdb",
    )


def test_manifest_schema_is_strict_and_version_locked() -> None:
    schema = postgres_migration_json_schema()
    assert schema["additionalProperties"] is False
    payload = _manifest().model_dump(mode="json")
    payload["contract"]["contract_version"] = "0.2.0"
    with pytest.raises(ValidationError):
        PostgresMigrationManifest.model_validate(payload)


def test_tampered_phase_is_blocked_before_runtime(tmp_path: Path) -> None:
    artifacts = _artifacts()
    artifacts["expand"] = PhaseArtifact(sql=_EXPAND + "\n-- tampered", rollback_sql=_EXPAND_ROLLBACK)
    receipt = verify_postgres_migration(
        _manifest(),
        _BASELINE,
        artifacts,
        binaries=_dummy_binaries(),
        workspace=tmp_path,
    )
    assert receipt.decision == "blocked"
    assert not receipt.source_bound
    assert {finding.code for finding in receipt.findings} == {"PG-SOURCE-SQL-DIGEST"}
    assert not list(tmp_path.iterdir())


def test_external_program_and_lock_lie_are_blocked_statically(tmp_path: Path) -> None:
    sql = "COPY app.accounts TO PROGRAM 'curl https://example.test';"
    rollback = "UPDATE app.accounts SET email = email;"
    manifest = _manifest(
        [
            _phase(
                "escape",
                sql,
                rollback,
                effect="data",
                lock=LockMode.ACCESS_SHARE.value,
            )
        ]
    )
    receipt = verify_postgres_migration(
        manifest,
        _BASELINE,
        {"escape": PhaseArtifact(sql=sql, rollback_sql=rollback)},
        binaries=_dummy_binaries(),
        workspace=tmp_path,
    )
    codes = {finding.code for finding in receipt.findings}
    assert receipt.decision == "blocked"
    assert "PG-STATIC-EXTERNAL-CAPABILITY" in codes
    assert "PG-STATIC-UNSUPPORTED-STATEMENT" in codes
    assert not list(tmp_path.iterdir())


def test_external_program_hidden_in_rollback_is_blocked_statically(tmp_path: Path) -> None:
    sql = "UPDATE app.accounts SET email = email;"
    rollback = "COPY app.accounts TO PROGRAM 'curl https://example.test';"
    manifest = _manifest(
        [
            _phase(
                "rollback-escape",
                sql,
                rollback,
                effect="data",
                lock=LockMode.ROW_EXCLUSIVE.value,
            )
        ]
    )
    receipt = verify_postgres_migration(
        manifest,
        _BASELINE,
        {"rollback-escape": PhaseArtifact(sql=sql, rollback_sql=rollback)},
        binaries=_dummy_binaries(),
        workspace=tmp_path,
    )
    assert receipt.decision == "blocked"
    assert "PG-STATIC-ROLLBACK-EXTERNAL-CAPABILITY" in {finding.code for finding in receipt.findings}
    assert not list(tmp_path.iterdir())


def test_baseline_metacommand_and_trigger_capability_are_blocked(tmp_path: Path) -> None:
    hostile_baseline = (
        _BASELINE
        + """
CREATE FUNCTION app.audit_accounts() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN RETURN NEW; END
$$;
CREATE TRIGGER accounts_audit AFTER UPDATE ON app.accounts
FOR EACH ROW EXECUTE FUNCTION app.audit_accounts();
\\! /usr/bin/false
"""
    )
    manifest = _manifest_for_baseline(
        hostile_baseline,
        [_phase("expand", _EXPAND, _EXPAND_ROLLBACK)],
        [{"schema_name": "app", "table_name": "accounts", "order_by": ["id"]}],
    )
    receipt = verify_postgres_migration(
        manifest,
        hostile_baseline,
        {"expand": PhaseArtifact(sql=_EXPAND, rollback_sql=_EXPAND_ROLLBACK)},
        binaries=_dummy_binaries(),
        workspace=tmp_path,
    )
    codes = {finding.code for finding in receipt.findings}
    assert receipt.decision == "blocked"
    assert "PG-STATIC-BASELINE-PSQL-META" in codes
    assert "PG-STATIC-BASELINE-CAPABILITY" in codes
    assert "PG-STATIC-BASELINE-FUNCTION-UNSUPPORTED" in codes
    assert not list(tmp_path.iterdir())


def test_second_table_mutation_is_not_hidden_by_declared_effect_category(
    tmp_path: Path,
) -> None:
    baseline = (
        _BASELINE
        + """
CREATE TABLE app.audit_log (id bigint PRIMARY KEY, note text NOT NULL);
INSERT INTO app.audit_log (id, note) VALUES (1, 'baseline');
"""
    )
    sql = """
UPDATE app.accounts SET email = email;
UPDATE app.audit_log SET note = 'changed';
"""
    rollback = """
UPDATE app.accounts SET email = email;
UPDATE app.audit_log SET note = 'baseline';
"""
    phases = [
        _phase(
            "scope-lie",
            sql,
            rollback,
            effect="data",
            lock=LockMode.ROW_EXCLUSIVE.value,
        )
    ]
    manifest = _manifest_for_baseline(
        baseline,
        phases,
        [
            {"schema_name": "app", "table_name": "accounts", "order_by": ["id"]},
            {"schema_name": "app", "table_name": "audit_log", "order_by": ["id"]},
        ],
    )
    receipt = verify_postgres_migration(
        manifest,
        baseline,
        {"scope-lie": PhaseArtifact(sql=sql, rollback_sql=rollback)},
        binaries=_dummy_binaries(),
        workspace=tmp_path,
    )
    assert receipt.decision == "blocked"
    assert "PG-STATIC-OBJECT-MISMATCH" in {finding.code for finding in receipt.findings}
    assert not list(tmp_path.iterdir())


def test_update_cannot_disable_timeouts_or_call_unbounded_functions(tmp_path: Path) -> None:
    sql = """
UPDATE app.accounts
SET email = pg_catalog.set_config('statement_timeout', '0', false);
UPDATE app.accounts SET email = pg_catalog.pg_sleep(1000)::text;
"""
    rollback = "UPDATE app.accounts SET email = email;"
    manifest = _manifest(
        [
            _phase(
                "session-escape",
                sql,
                rollback,
                effect="data",
                lock=LockMode.ROW_EXCLUSIVE.value,
            )
        ]
    )
    receipt = verify_postgres_migration(
        manifest,
        _BASELINE,
        {"session-escape": PhaseArtifact(sql=sql, rollback_sql=rollback)},
        binaries=_dummy_binaries(),
        workspace=tmp_path,
    )
    assert receipt.decision == "blocked"
    assert "PG-STATIC-FUNCTION-UNSUPPORTED" in {finding.code for finding in receipt.findings}
    assert not list(tmp_path.iterdir())


def test_compound_alter_cannot_smuggle_row_security_state(tmp_path: Path) -> None:
    sql = """
ALTER TABLE app.accounts
  ADD COLUMN display_name text,
  ENABLE ROW LEVEL SECURITY,
  FORCE ROW LEVEL SECURITY;
"""
    rollback = "ALTER TABLE app.accounts DROP COLUMN display_name;"
    manifest = _manifest([_phase("rls-lie", sql, rollback)])
    receipt = verify_postgres_migration(
        manifest,
        _BASELINE,
        {"rls-lie": PhaseArtifact(sql=sql, rollback_sql=rollback)},
        binaries=_dummy_binaries(),
        workspace=tmp_path,
    )
    assert receipt.decision == "blocked"
    assert "PG-STATIC-COMPOUND-ALTER-UNSUPPORTED" in {finding.code for finding in receipt.findings}
    phase = receipt.phases[0]
    assert phase.declared_objects == ["app.accounts"]
    assert phase.static_objects == ["app.accounts"]
    assert not list(tmp_path.iterdir())


@pytest.mark.parametrize(
    "expression",
    [
        "\"set_config\"('statement_timeout', '0', false)",
        '"lo_create"(424242)::text',
    ],
)
def test_quoted_function_names_are_rejected(expression: str, tmp_path: Path) -> None:
    sql = f"UPDATE app.accounts SET email = {expression};"
    rollback = "UPDATE app.accounts SET email = email;"
    manifest = _manifest(
        [
            _phase(
                "quoted-call",
                sql,
                rollback,
                effect="data",
                lock=LockMode.ROW_EXCLUSIVE.value,
            )
        ]
    )
    receipt = verify_postgres_migration(
        manifest,
        _BASELINE,
        {"quoted-call": PhaseArtifact(sql=sql, rollback_sql=rollback)},
        binaries=_dummy_binaries(),
        workspace=tmp_path,
    )
    assert receipt.decision == "blocked"
    assert "PG-STATIC-QUOTED-IDENTIFIER" in {finding.code for finding in receipt.findings}
    assert not list(tmp_path.iterdir())


def test_sequence_probe_and_baseline_insert_cannot_amplify_rows(tmp_path: Path) -> None:
    sql = "SELECT nextval('app.accounts_id_seq') FROM pg_catalog.pg_class a, pg_catalog.pg_class b;"
    rollback = "SELECT setval('app.accounts_id_seq', 1, false);"
    manifest = _manifest(
        [
            _phase(
                "sequence-amplifier",
                sql,
                rollback,
                effect="sequence",
                lock=LockMode.ROW_EXCLUSIVE.value,
                expected_object="app.accounts_id_seq",
            )
        ]
    )
    receipt = verify_postgres_migration(
        manifest,
        _BASELINE,
        {"sequence-amplifier": PhaseArtifact(sql=sql, rollback_sql=rollback)},
        binaries=_dummy_binaries(),
        workspace=tmp_path,
    )
    assert "PG-STATIC-SEQUENCE-SCOPE-UNSUPPORTED" in {finding.code for finding in receipt.findings}

    amplifying_baseline = """
CREATE SCHEMA app;
CREATE TABLE app.accounts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email text NOT NULL
);
INSERT INTO app.accounts (email) SELECT relname FROM pg_catalog.pg_class;
"""
    baseline_manifest = _manifest_for_baseline(
        amplifying_baseline,
        [_phase("expand", _EXPAND, _EXPAND_ROLLBACK)],
        [{"schema_name": "app", "table_name": "accounts", "order_by": ["id"]}],
    )
    baseline_receipt = verify_postgres_migration(
        baseline_manifest,
        amplifying_baseline,
        {"expand": PhaseArtifact(sql=_EXPAND, rollback_sql=_EXPAND_ROLLBACK)},
        binaries=_dummy_binaries(),
        workspace=tmp_path,
    )
    assert baseline_receipt.decision == "blocked"
    assert "PG-STATIC-BASELINE-UNSUPPORTED" in {finding.code for finding in baseline_receipt.findings}
    assert not list(tmp_path.iterdir())


@pytest.mark.parametrize(
    "baseline",
    [
        """
CREATE SCHEMA app;
CREATE TABLE app.accounts AS
SELECT a.oid AS id, a.relname AS email
FROM pg_catalog.pg_class a, pg_catalog.pg_class b;
""",
        """
CREATE SCHEMA app;
CREATE TABLE app.accounts (id, email) AS VALUES (1, 'x');
""",
        """
CREATE SCHEMA app;
CREATE TABLE app.accounts (id, email) AS TABLE pg_catalog.pg_class;
""",
        """
CREATE SCHEMA app;
CREATE TABLE app.accounts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email text NOT NULL
);
INSERT INTO app.accounts (email) VALUES ('x')
RETURNING email, email, email, email;
""",
    ],
)
def test_baseline_create_as_and_returning_are_blocked(baseline: str, tmp_path: Path) -> None:
    manifest = _manifest_for_baseline(
        baseline,
        [_phase("expand", _EXPAND, _EXPAND_ROLLBACK)],
        [{"schema_name": "app", "table_name": "accounts", "order_by": ["id"]}],
    )
    receipt = verify_postgres_migration(
        manifest,
        baseline,
        {"expand": PhaseArtifact(sql=_EXPAND, rollback_sql=_EXPAND_ROLLBACK)},
        binaries=_dummy_binaries(),
        workspace=tmp_path,
    )
    assert receipt.decision == "blocked"
    assert "PG-STATIC-BASELINE-UNSUPPORTED" in {finding.code for finding in receipt.findings}
    assert not list(tmp_path.iterdir())


def test_wide_many_row_baseline_is_blocked_before_snapshot(tmp_path: Path) -> None:
    columns = ", ".join(f"c{index} int" for index in range(1, 34))
    rows = ", ".join("(1)" for _ in range(101))
    oversized_literal = "x" * 16_385
    baseline = f"""
CREATE SCHEMA app;
CREATE TABLE app.accounts ({columns}, note text DEFAULT '{oversized_literal}');
INSERT INTO app.accounts (c1) VALUES {rows};
"""
    manifest = _manifest_for_baseline(
        baseline,
        [_phase("expand", _EXPAND, _EXPAND_ROLLBACK)],
        [{"schema_name": "app", "table_name": "accounts", "order_by": ["c1"]}],
    )
    receipt = verify_postgres_migration(
        manifest,
        baseline,
        {"expand": PhaseArtifact(sql=_EXPAND, rollback_sql=_EXPAND_ROLLBACK)},
        binaries=_dummy_binaries(),
        workspace=tmp_path,
    )
    codes = {finding.code for finding in receipt.findings}
    assert receipt.decision == "blocked"
    assert "PG-STATIC-BASELINE-COLUMN-LIMIT" in codes
    assert "PG-STATIC-BASELINE-ROW-LIMIT" in codes
    assert "PG-STATIC-BASELINE-LITERAL-SIZE" in codes
    assert not list(tmp_path.iterdir())


def test_phase_cannot_cross_the_live_column_budget(tmp_path: Path) -> None:
    columns = ", ".join(f"c{index} int" for index in range(1, 33))
    baseline = f"""
CREATE SCHEMA app;
CREATE TABLE app.accounts ({columns});
INSERT INTO app.accounts (c1) VALUES (1);
"""
    sql = "ALTER TABLE app.accounts ADD COLUMN c33 int;"
    rollback = "ALTER TABLE app.accounts DROP COLUMN c33;"
    manifest = _manifest_for_baseline(
        baseline,
        [_phase("column-overflow", sql, rollback)],
        [{"schema_name": "app", "table_name": "accounts", "order_by": ["c1"]}],
    )
    receipt = verify_postgres_migration(
        manifest,
        baseline,
        {"column-overflow": PhaseArtifact(sql=sql, rollback_sql=rollback)},
        binaries=_dummy_binaries(),
        workspace=tmp_path,
    )
    assert receipt.decision == "blocked"
    assert "PG-STATIC-LIVE-COLUMN-LIMIT" in {finding.code for finding in receipt.findings}
    assert not list(tmp_path.iterdir())

    apply_transient = """
ALTER TABLE app.accounts ADD COLUMN c33 int;
ALTER TABLE app.accounts DROP COLUMN c1;
"""
    apply_rollback = """
ALTER TABLE app.accounts ADD COLUMN c1 int;
ALTER TABLE app.accounts DROP COLUMN c33;
"""
    transient_manifest = _manifest_for_baseline(
        baseline,
        [_phase("apply-transient", apply_transient, apply_rollback)],
        [{"schema_name": "app", "table_name": "accounts", "order_by": ["c1"]}],
    )
    transient_receipt = verify_postgres_migration(
        transient_manifest,
        baseline,
        {"apply-transient": PhaseArtifact(sql=apply_transient, rollback_sql=apply_rollback)},
        binaries=_dummy_binaries(),
        workspace=tmp_path,
    )
    assert "PG-STATIC-LIVE-COLUMN-LIMIT" in {finding.code for finding in transient_receipt.findings}

    rollback_safe_apply = """
ALTER TABLE app.accounts DROP COLUMN c1;
ALTER TABLE app.accounts ADD COLUMN c33 int;
"""
    rollback_transient = """
ALTER TABLE app.accounts ADD COLUMN c1 int;
ALTER TABLE app.accounts DROP COLUMN c33;
"""
    rollback_manifest = _manifest_for_baseline(
        baseline,
        [_phase("rollback-transient", rollback_safe_apply, rollback_transient)],
        [{"schema_name": "app", "table_name": "accounts", "order_by": ["c1"]}],
    )
    rollback_receipt = verify_postgres_migration(
        rollback_manifest,
        baseline,
        {"rollback-transient": PhaseArtifact(sql=rollback_safe_apply, rollback_sql=rollback_transient)},
        binaries=_dummy_binaries(),
        workspace=tmp_path,
    )
    assert "PG-STATIC-LIVE-COLUMN-LIMIT" in {finding.code for finding in rollback_receipt.findings}
    assert not list(tmp_path.iterdir())


def test_phase_count_bundle_bytes_and_runtime_deadline_are_bounded(tmp_path: Path) -> None:
    base_phase = _phase(
        "phase-0",
        "UPDATE app.accounts SET email = email;",
        "UPDATE app.accounts SET email = email;",
        effect="data",
        lock=LockMode.ROW_EXCLUSIVE.value,
    )
    payload = _manifest([base_phase]).model_dump(mode="json")
    payload["phases"] = [{**base_phase, "phase_id": f"phase-{index}"} for index in range(9)]
    with pytest.raises(ValidationError):
        PostgresMigrationManifest.model_validate(payload)

    padding = "p" * 199_900
    phases: list[dict[str, object]] = []
    artifacts: dict[str, PhaseArtifact] = {}
    for index in range(3):
        sql = f"UPDATE app.accounts SET email = email;\n-- {padding}-{index}"
        rollback = f"UPDATE app.accounts SET email = email;\n-- {padding}-r{index}"
        phase_id = f"bundle-{index}"
        phases.append(
            _phase(
                phase_id,
                sql,
                rollback,
                effect="data",
                lock=LockMode.ROW_EXCLUSIVE.value,
            )
        )
        artifacts[phase_id] = PhaseArtifact(sql=sql, rollback_sql=rollback)
    receipt = verify_postgres_migration(
        _manifest(phases),
        _BASELINE,
        artifacts,
        binaries=_dummy_binaries(),
        workspace=tmp_path,
    )
    assert "PG-SOURCE-BUNDLE-SIZE" in {finding.code for finding in receipt.findings}

    cluster = _DisposablePostgres(_dummy_binaries(), tmp_path, deadline=time.monotonic() - 1)
    with pytest.raises(subprocess.TimeoutExpired):
        cluster._run([Path("/bin/sleep"), "5"], database=None, timeout=30)

    repeated_baseline = _BASELINE + "\n".join(
        f"INSERT INTO app.accounts (email) VALUES ('extra-{index}');" for index in range(24)
    )
    repeated_manifest = _manifest_for_baseline(
        repeated_baseline,
        [_phase("expand", _EXPAND, _EXPAND_ROLLBACK)],
        [{"schema_name": "app", "table_name": "accounts", "order_by": ["id"]}],
    )
    repeated_receipt = verify_postgres_migration(
        repeated_manifest,
        repeated_baseline,
        {"expand": PhaseArtifact(sql=_EXPAND, rollback_sql=_EXPAND_ROLLBACK)},
        binaries=_dummy_binaries(),
        workspace=tmp_path,
    )
    assert "PG-STATIC-BASELINE-TOTAL-ROW-LIMIT" in {finding.code for finding in repeated_receipt.findings}
    assert not list(tmp_path.iterdir())


@requires_postgres
def test_benign_expand_contract_reaches_verified_rollback(tmp_path: Path) -> None:
    assert _BINDIR is not None
    receipt = verify_postgres_migration(
        _manifest(),
        _BASELINE,
        _artifacts(),
        binaries=PostgresBinaries.from_bindir(_BINDIR),
        workspace=tmp_path,
    )
    assert receipt.decision == "eligible", receipt.model_dump_json(indent=2)
    assert receipt.source_bound
    assert receipt.preview_matches_actual is True
    assert receipt.rollback_verified is True
    assert receipt.cleanup_verified
    assert receipt.role_evidence is not None
    assert receipt.role_evidence.observed_current_user == "proofos_migrator"
    assert not receipt.role_evidence.superuser
    assert set(receipt.binary_digests) == {
        "postgres",
        "initdb",
        "pg_ctl",
        "psql",
        "createdb",
        "dropdb",
    }
    assert receipt.baseline_state_digest == receipt.rollback_state_digest
    assert receipt.preview_state_digest == receipt.actual_state_digest
    assert all(
        phase.transaction_rollback_clean is True for phase in receipt.phases if phase.phase_id != "index"
    )
    assert [phase.observed_objects for phase in receipt.phases] == [
        ["app.accounts"],
        ["app.accounts"],
        ["app.accounts_email_lower_idx"],
    ]
    assert [phase.rollback_observed_objects for phase in receipt.phases] == [
        ["app.accounts"],
        ["app.accounts"],
        ["app.accounts_email_lower_idx"],
    ]
    assert not list(tmp_path.iterdir())


@requires_postgres
def test_entry_failure_still_removes_disposable_state(tmp_path: Path) -> None:
    assert _BINDIR is not None
    binaries = PostgresBinaries.from_bindir(_BINDIR).model_copy(update={"initdb": Path("/usr/bin/false")})
    receipt = verify_postgres_migration(
        _manifest(),
        _BASELINE,
        _artifacts(),
        binaries=binaries,
        workspace=tmp_path,
    )
    assert receipt.decision == "blocked"
    assert "PG-RUNTIME-EXECUTION-FAILED" in {finding.code for finding in receipt.findings}
    assert receipt.cleanup_verified
    assert not list(tmp_path.iterdir())


def test_unverified_stop_preserves_state_and_fails_cleanup(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    cluster = _DisposablePostgres(_dummy_binaries(), tmp_path)
    cluster.root = tmp_path / "cluster"
    cluster.data_dir = cluster.root / "data"
    cluster.home_dir = cluster.root / "home"
    cluster.socket_dir = tmp_path / "socket"
    cluster.root.mkdir()
    cluster.data_dir.mkdir()
    cluster.home_dir.mkdir()
    cluster.socket_dir.mkdir()
    (cluster.data_dir / "postmaster.pid").write_text("synthetic", encoding="utf-8")
    cluster.started = True

    def fail_stop(*args: object, **kwargs: object) -> None:
        raise RuntimeError("synthetic stop failure")

    monkeypatch.setattr(cluster, "_run", fail_stop)
    cluster._teardown()
    assert not cluster.cleanup_verified
    assert cluster.root.exists()
    assert cluster.socket_dir.exists()
    assert any("state was preserved" in error for error in cluster.cleanup_errors)


def test_process_output_is_killed_at_the_byte_ceiling() -> None:
    process = subprocess.Popen(
        [sys.executable, "-c", "import sys; sys.stdout.write('x' * 9_000_000)"],
        stdin=subprocess.DEVNULL,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    with pytest.raises(RuntimeError, match="output byte cap"):
        _bounded_process_output(process, timeout=10)
    assert process.returncode is not None


@requires_postgres
def test_sequence_side_effect_disproves_transaction_rollback_claim(tmp_path: Path) -> None:
    assert _BINDIR is not None
    sql = "SELECT nextval('app.accounts_id_seq');"
    rollback = "SELECT setval('app.accounts_id_seq', 1, false);"
    manifest = _manifest(
        [
            _phase(
                "sequence-lie",
                sql,
                rollback,
                effect="sequence",
                lock=LockMode.ROW_EXCLUSIVE.value,
                expected_object="app.accounts_id_seq",
            )
        ]
    )
    receipt = verify_postgres_migration(
        manifest,
        _BASELINE,
        {"sequence-lie": PhaseArtifact(sql=sql, rollback_sql=rollback)},
        binaries=PostgresBinaries.from_bindir(_BINDIR),
        workspace=tmp_path,
    )
    assert receipt.decision == "blocked"
    assert "PG-RUNTIME-TRANSACTION-ROLLBACK-DIRTY" in {finding.code for finding in receipt.findings}
    assert receipt.cleanup_verified
    assert not list(tmp_path.iterdir())


@requires_postgres
def test_psql_script_file_avoids_full_duplex_pipe_deadlock(tmp_path: Path) -> None:
    assert _BINDIR is not None
    literal_piece = "'" + ("x" * 15_000) + "'"
    large_expression = " || ".join(literal_piece for _ in range(7))
    padding = "p" * 120_000
    sql = f"SELECT {large_expression}, nextval('app.accounts_id_seq');\n-- {padding}"
    rollback = "SELECT setval('app.accounts_id_seq', 1, false);"
    manifest = _manifest(
        [
            _phase(
                "bounded-io",
                sql,
                rollback,
                effect="sequence",
                lock=LockMode.ROW_EXCLUSIVE.value,
                expected_object="app.accounts_id_seq",
            )
        ]
    )
    receipt = verify_postgres_migration(
        manifest,
        _BASELINE,
        {"bounded-io": PhaseArtifact(sql=sql, rollback_sql=rollback)},
        binaries=PostgresBinaries.from_bindir(_BINDIR),
        workspace=tmp_path,
    )
    assert receipt.decision == "blocked"
    assert "PG-RUNTIME-TRANSACTION-ROLLBACK-DIRTY" in {finding.code for finding in receipt.findings}
    assert receipt.cleanup_verified
    assert not list(tmp_path.iterdir())


@requires_postgres
def test_preview_actual_mutation_mismatch_is_blocked(tmp_path: Path) -> None:
    assert _BINDIR is not None
    sql = "UPDATE app.accounts SET email = pg_catalog.txid_current()::text;"
    rollback = """
UPDATE app.accounts
SET email = CASE id
  WHEN 1 THEN 'ada@example.test'
  WHEN 2 THEN 'grace@example.test'
END;
"""
    manifest = _manifest(
        [
            _phase(
                "preview-lie",
                sql,
                rollback,
                effect="data",
                lock=LockMode.ROW_EXCLUSIVE.value,
            )
        ]
    )
    receipt = verify_postgres_migration(
        manifest,
        _BASELINE,
        {"preview-lie": PhaseArtifact(sql=sql, rollback_sql=rollback)},
        binaries=PostgresBinaries.from_bindir(_BINDIR),
        workspace=tmp_path,
    )
    assert receipt.decision == "blocked"
    assert receipt.preview_matches_actual is False
    assert "PG-RUNTIME-PREVIEW-ACTUAL-MISMATCH" in {finding.code for finding in receipt.findings}
    assert receipt.cleanup_verified
    assert not list(tmp_path.iterdir())


@requires_postgres
def test_successful_but_deceptive_rollback_is_blocked(tmp_path: Path) -> None:
    assert _BINDIR is not None
    deceptive = _artifacts()
    deceptive["expand"] = PhaseArtifact(
        sql=_EXPAND,
        rollback_sql="ALTER TABLE app.accounts DROP CONSTRAINT accounts_display_name_len;",
    )
    phases = _manifest().model_dump(mode="json")["phases"]
    phases[0]["rollback_digest"] = digest_bytes(deceptive["expand"].rollback_sql.encode())
    receipt = verify_postgres_migration(
        _manifest(phases),
        _BASELINE,
        deceptive,
        binaries=PostgresBinaries.from_bindir(_BINDIR),
        workspace=tmp_path,
    )
    assert receipt.decision == "blocked"
    assert "PG-ROLLBACK-STATE-MISMATCH" in {finding.code for finding in receipt.findings}
    assert receipt.rollback_verified is False
    assert receipt.cleanup_verified
    assert not list(tmp_path.iterdir())
