FROM gcr.io/oss-fuzz-base/base-builder-python@sha256:d4ef5a787f3e1a420721da74823202185dc04e2e792984671c31a67d7ce66832

COPY . $SRC/MCPAudit
WORKDIR $SRC/MCPAudit
COPY ./.clusterfuzzlite/build.sh $SRC/
