"""Single-file HTML report generator for mcp-audit.

Produces a self-contained, shareable HTML document from an ``AuditReport`` —
inline CSS, no JavaScript, no external resources, so it renders offline and can
be emailed or attached to a ticket as-is.

Security notes:
  * The report is built from a redacted copy of the audit (``redact_data``), so
    no credential value can leak even if one reached the model layer.
  * EVERY dynamic value is HTML-escaped via ``html.escape``. Tool descriptions
    are attacker-influenceable and may contain ``<script>`` or other markup; the
    report must never become an XSS vector when opened in a browser.
"""

from __future__ import annotations

from html import escape
from typing import Any

from mcp_audit.models import AuditReport, ServerAudit
from mcp_audit.redaction import redact_data

_SEVERITY_CLASS = {
    "high": "sev-high",
    "medium": "sev-medium",
    "low": "sev-low",
}

_STYLE = """
:root { color-scheme: light dark; }
* { box-sizing: border-box; }
body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
       margin: 0; padding: 2rem; line-height: 1.5; color: #1a1a1a; background: #fafafa; }
h1 { font-size: 1.6rem; margin: 0 0 0.25rem; }
h2 { font-size: 1.2rem; margin: 2rem 0 0.75rem; border-bottom: 2px solid #e0e0e0; padding-bottom: 0.25rem; }
h3 { font-size: 1.0rem; margin: 1.25rem 0 0.5rem; }
.subtitle { color: #666; margin: 0 0 1.5rem; font-size: 0.9rem; }
.summary { display: flex; flex-wrap: wrap; gap: 1rem; margin: 1rem 0; }
.stat { background: #fff; border: 1px solid #e0e0e0; border-radius: 8px; padding: 0.75rem 1rem;
        min-width: 7rem; }
.stat .num { font-size: 1.5rem; font-weight: 700; }
.stat .label { font-size: 0.75rem; color: #666; text-transform: uppercase; letter-spacing: 0.03em; }
table { border-collapse: collapse; width: 100%; margin: 0.5rem 0 1rem; background: #fff; font-size: 0.88rem; }
th, td { text-align: left; padding: 0.45rem 0.6rem; border: 1px solid #e6e6e6; vertical-align: top; }
th { background: #f2f2f2; font-weight: 600; }
code { font-family: ui-monospace, "SF Mono", Menlo, monospace; font-size: 0.85em; }
.server { background: #fff; border: 1px solid #e0e0e0; border-radius: 8px; padding: 1rem 1.25rem;
          margin: 1rem 0; }
.server-head { display: flex; align-items: baseline; gap: 0.75rem; flex-wrap: wrap; }
.badge { display: inline-block; padding: 0.1rem 0.5rem; border-radius: 999px; font-size: 0.72rem;
         font-weight: 600; text-transform: uppercase; letter-spacing: 0.03em; }
.sev-high { background: #fde7e7; color: #a01313; }
.sev-medium { background: #fdf3e0; color: #9a6300; }
.sev-low { background: #e8f0fe; color: #2a51a8; }
.ok { background: #e6f5ea; color: #1c7c38; }
.muted { color: #888; }
.empty { color: #888; font-style: italic; margin: 0.25rem 0 1rem; }
.policy-pass { color: #1c7c38; font-weight: 600; }
.policy-fail { color: #a01313; font-weight: 600; }
footer { margin-top: 2.5rem; color: #999; font-size: 0.78rem; }
@media (prefers-color-scheme: dark) {
  body { color: #e6e6e6; background: #161616; }
  .stat, .server, table { background: #1f1f1f; border-color: #333; }
  th { background: #262626; }
  h2 { border-color: #333; }
}
"""


class HtmlReportGenerator:
    """Converts an ``AuditReport`` into a single self-contained HTML string."""

    def generate(self, report: AuditReport) -> str:
        """Return the full HTML document. Caller writes it to disk."""
        report = AuditReport.model_validate(redact_data(report.model_dump(mode="json")))
        parts: list[str] = [
            "<!DOCTYPE html>",
            '<html lang="en"><head><meta charset="utf-8">',
            '<meta name="viewport" content="width=device-width, initial-scale=1">',
            "<title>mcp-audit report</title>",
            f"<style>{_STYLE}</style>",
            "</head><body>",
            "<h1>MCP Permission Audit</h1>",
            (
                f'<p class="subtitle">{self._esc(report.hostname)} · '
                f"{self._esc(report.os_platform)} · scanned "
                f"{self._esc(report.scan_timestamp.isoformat())} · "
                f"{report.scan_duration_seconds:.2f}s</p>"
            ),
            self._summary(report),
            self._policy(report),
            self._config_health(report),
        ]
        for audit in report.audits:
            parts.append(self._server(audit))
        parts.append(self._fleet(report))
        parts.append(
            "<footer>Generated by mcp-audit. Env var values are never captured; "
            "only key names appear in any output.</footer>"
        )
        parts.append("</body></html>")
        return "\n".join(parts)

    # ------------------------------------------------------------------
    # Sections
    # ------------------------------------------------------------------

    def _summary(self, report: AuditReport) -> str:
        stats = [
            ("Discovered", report.servers_discovered),
            ("Connected", report.servers_connected),
            ("Failed", report.servers_failed),
            ("Tools", report.total_tools),
            ("High-risk servers", report.high_risk_servers),
        ]
        cells = "".join(
            f'<div class="stat"><div class="num">{value}</div>'
            f'<div class="label">{self._esc(label)}</div></div>'
            for label, value in stats
        )
        return f'<div class="summary">{cells}</div>'

    def _server(self, audit: ServerAudit) -> str:
        srv = audit.server
        composite = audit.risk_score.composite if audit.risk_score else 0.0
        risk_badge = self._severity_badge_for_score(composite)
        head = (
            '<div class="server-head">'
            f"<h3>{self._esc(srv.name)}</h3>"
            f'<span class="badge muted">{self._esc(srv.client.value)}</span>'
            f'<span class="badge muted">{self._esc(srv.transport.value)}</span>'
            f'<span class="badge {self._status_class(audit.connection_status)}">'
            f"{self._esc(audit.connection_status)}</span>"
            f'<span class="badge {risk_badge}">risk {composite:.1f}</span>'
            "</div>"
        )
        body = [head]
        if audit.connection_error:
            body.append(f'<p class="muted">Error: {self._esc(audit.connection_error)}</p>')

        body.append(self._permissions_table(audit))
        body.append(self._injection_table(audit))
        body.append(self._ssrf_table(audit))
        body.append(self._trifecta_table(audit))
        body.append(self._escalation_table(audit))
        body.append(self._provenance_table(audit))
        body.append(self._integrity_table(audit))
        body.append(self._package_verify_table(audit))
        body.append(self._drift_table(audit))
        return f'<div class="server">{"".join(body)}</div>'

    def _permissions_table(self, audit: ServerAudit) -> str:
        rows = [
            self._row(
                self._sev_badge(f.severity),
                self._esc(f.rule_id),
                self._esc(f.category.value),
                self._esc(f.tool_name),
                self._esc(f.confidence.value),
                self._esc("; ".join(f.evidence)),
            )
            for f in audit.permissions
        ]
        return self._table(
            "Permissions",
            ["Severity", "Rule", "Category", "Tool", "Confidence", "Evidence"],
            rows,
        )

    def _injection_table(self, audit: ServerAudit) -> str:
        rows = [
            self._row(
                self._sev_badge(f.severity.value),
                self._esc(f.rule_id),
                self._esc(f.pattern_name),
                self._esc(f.target_name or f.tool_name),
                self._esc(f.matched_text),
            )
            for f in audit.injection_findings
        ]
        return self._table(
            "Prompt-injection", ["Severity", "Rule", "Pattern", "Target", "Matched text"], rows
        )

    def _ssrf_table(self, audit: ServerAudit) -> str:
        rows = [
            self._row(
                self._sev_badge(f.severity.value),
                self._esc(f.rule_id),
                self._esc(f.pattern_name),
                self._esc(f.target_name),
                self._esc("; ".join(f.evidence)),
            )
            for f in audit.ssrf_findings
        ]
        return self._table("SSRF", ["Severity", "Rule", "Pattern", "Target", "Evidence"], rows)

    def _trifecta_table(self, audit: ServerAudit) -> str:
        rows = [
            self._row(
                self._sev_badge(f.severity.value),
                self._esc(f.rule_id),
                self._esc(self._pairs(f.leg1_contributors)),
                self._esc(self._pairs(f.leg2_contributors)),
                self._esc(self._pairs(f.leg3_contributors)),
            )
            for f in audit.trifecta_findings
        ]
        return self._table(
            "Lethal trifecta",
            ["Severity", "Rule", "Leg 1 (read)", "Leg 2 (ingest)", "Leg 3 (exfil)"],
            rows,
        )

    def _escalation_table(self, audit: ServerAudit) -> str:
        rows = [
            self._row(
                self._sev_badge(f.severity.value),
                self._esc(f.rule_id),
                self._esc(f.kind.value),
                self._esc(f.tool_name),
                self._esc(", ".join(c.value for c in f.gained_categories) or ", ".join(f.gained_patterns)),
            )
            for f in audit.escalation_findings
        ]
        return self._table(
            "Capability escalation (vs pin baseline)",
            ["Severity", "Rule", "Kind", "Tool", "Gained"],
            rows,
        )

    def _provenance_table(self, audit: ServerAudit) -> str:
        rows = [
            self._row(
                self._sev_badge(f.severity.value),
                self._esc(f.rule_id),
                self._esc(f.kind.value),
                self._esc(f.summary),
            )
            for f in audit.provenance_findings
        ]
        return self._table(
            "Provenance / launch-config drift (vs pin baseline)",
            ["Severity", "Rule", "Kind", "Change"],
            rows,
        )

    def _integrity_table(self, audit: ServerAudit) -> str:
        rows = [
            self._row(
                self._sev_badge(f.severity.value),
                self._esc(f.rule_id),
                self._esc(f.artifact_path),
                self._esc(f.summary),
            )
            for f in audit.integrity_findings
        ]
        return self._table(
            "Launch-artifact integrity (vs pin baseline)",
            ["Severity", "Rule", "Artifact", "Change"],
            rows,
        )

    def _package_verify_table(self, audit: ServerAudit) -> str:
        rows = [
            self._row(
                self._sev_badge(f.severity.value),
                self._esc(f.rule_id),
                self._esc(f"{f.ecosystem}:{f.package}@{f.version}"),
                self._esc(f.summary),
            )
            for f in audit.package_verify_findings
        ]
        return self._table(
            "Registry package verification (vs pin baseline)",
            ["Severity", "Rule", "Package", "Change"],
            rows,
        )

    def _drift_table(self, audit: ServerAudit) -> str:
        rows = [
            self._row(
                self._esc(f.status.value),
                self._esc(f.tool_name),
                self._esc(f.summary),
                self._esc("; ".join(f.details)),
            )
            for f in audit.drift_findings
        ]
        return self._table("Schema drift", ["Status", "Tool", "Summary", "Details"], rows)

    def _fleet(self, report: AuditReport) -> str:
        fleet_trifecta_rows = [
            self._row(
                self._sev_badge(f.severity.value),
                self._esc(f.rule_id),
                self._esc(self._pairs(f.leg1_contributors)),
                self._esc(self._pairs(f.leg2_contributors)),
                self._esc(self._pairs(f.leg3_contributors)),
            )
            for f in report.fleet_trifecta_findings
        ]
        shadowing_rows = [
            self._row(
                self._sev_badge(f.severity.value),
                self._esc(f.rule_id),
                self._esc(f.kind.value),
                self._esc(f.name),
                self._esc(self._pairs(f.collisions)),
            )
            for f in report.shadowing_findings
        ]
        out = ["<h2>Fleet-level findings</h2>"]
        out.append(
            self._table(
                "Fleet lethal trifecta (advisory)",
                ["Severity", "Rule", "Leg 1", "Leg 2", "Leg 3"],
                fleet_trifecta_rows,
                level=3,
            )
        )
        out.append(
            self._table(
                "Tool-name shadowing",
                ["Severity", "Rule", "Kind", "Name", "Colliding server/tool"],
                shadowing_rows,
                level=3,
            )
        )
        return "".join(out)

    def _config_health(self, report: AuditReport) -> str:
        rows = [
            self._row(
                self._sev_badge(f.severity.value),
                self._esc(f.finding_type),
                self._esc(f.server_name or "—"),
                self._esc(f.summary),
                self._esc(f.remediation),
            )
            for f in report.config_health_findings
        ]
        return self._table("Config health", ["Severity", "Type", "Server", "Summary", "Remediation"], rows)

    def _policy(self, report: AuditReport) -> str:
        result = report.policy_result
        if result is None:
            return ""
        status = (
            '<span class="policy-pass">PASSED</span>'
            if result.passed
            else '<span class="policy-fail">FAILED</span>'
        )
        rows = [
            self._row(
                self._sev_badge(v.severity),
                self._esc(v.rule),
                self._esc(v.server_name or "—"),
                self._esc(v.tool_name or "—"),
                self._esc(v.message),
            )
            for v in result.violations
        ]
        heading = f"<h2>Policy: {status}</h2>"
        if not rows:
            return f'{heading}<p class="empty">No violations.</p>'
        body = self._table_body(["Severity", "Rule", "Server", "Tool", "Message"], rows)
        return f"{heading}{body}"

    # ------------------------------------------------------------------
    # HTML helpers
    # ------------------------------------------------------------------

    def _table(self, title: str, headers: list[str], rows: list[str], level: int = 2) -> str:
        tag = f"h{level}"
        heading = f"<{tag}>{self._esc(title)}</{tag}>"
        if not rows:
            return f'{heading}<p class="empty">None.</p>'
        return heading + self._table_body(headers, rows)

    def _table_body(self, headers: list[str], rows: list[str]) -> str:
        head = "".join(f"<th>{self._esc(h)}</th>" for h in headers)
        return f"<table><thead><tr>{head}</tr></thead><tbody>{''.join(rows)}</tbody></table>"

    def _row(self, *cells: str) -> str:
        # Cells are pre-escaped (or trusted badge/markup) by the caller.
        return "<tr>" + "".join(f"<td>{c}</td>" for c in cells) + "</tr>"

    def _sev_badge(self, severity: str) -> str:
        cls = _SEVERITY_CLASS.get(severity, "muted")
        return f'<span class="badge {cls}">{self._esc(severity)}</span>'

    def _severity_badge_for_score(self, composite: float) -> str:
        if composite >= 7.0:
            return "sev-high"
        if composite >= 3.0:
            return "sev-medium"
        return "sev-low"

    def _status_class(self, status: str) -> str:
        return "ok" if status == "connected" else "muted"

    def _pairs(self, pairs: list[Any]) -> str:
        return "; ".join(f"{srv}/{tool}" for srv, tool in pairs)

    def _esc(self, value: str) -> str:
        return escape(value, quote=True)
