name: ClusterFuzzLite PR fuzzing

on:
  pull_request:
    paths:
      - ".clusterfuzzlite/**"
      - ".github/workflows/cflite_pr.yml"
      - "fuzz/**"
      - "pyproject.toml"
      - "src/**"
      - "tests/**"
      - "uv.lock"

permissions: read-all

jobs:
  fuzz:
    name: ClusterFuzzLite (${{ matrix.sanitizer }})
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ matrix.sanitizer }}-${{ github.ref }}
      cancel-in-progress: true
    strategy:
      fail-fast: false
      matrix:
        sanitizer:
          - address
    steps:
      - name: Build fuzzers
        id: build
        uses: google/clusterfuzzlite/actions/build_fuzzers@82652fb49e77bc29c35da1167bb286e93c6bcc05 # v1
        with:
          language: python
          github-token: ${{ secrets.GITHUB_TOKEN }}
          sanitizer: ${{ matrix.sanitizer }}

      - name: Run fuzzers
        id: run
        uses: google/clusterfuzzlite/actions/run_fuzzers@82652fb49e77bc29c35da1167bb286e93c6bcc05 # v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fuzz-seconds: 120
          mode: code-change
          sanitizer: ${{ matrix.sanitizer }}
          output-sarif: true
