name: OpenSSF Scorecard

on:
  branch_protection_rule:
  schedule:
    - cron: "37 13 * * 1"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  scorecard:
    name: Scorecard
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Run OpenSSF Scorecard
        uses: ossf/scorecard-action@v2.4.3
        with:
          results_file: scorecard.sarif
          results_format: sarif
          publish_results: true

      - name: Upload SARIF to code scanning
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: scorecard.sarif
